### ISSUE TITLE
Это разве не build type варсы?

### ISSUE THREAD

**Issue by heavycharged** [ArtemiyKroshka/golang_project#6]
https://github.com/ArtemiyKroshka/golang_project/blob/09dc12a9da30841bfbf9e7743d1d1a7fde0a5452/Dockerfile#L19C1-L24C1

Эти переменные будут юзаться на этапе сборки (когда ещё делается имедж), а не на этапе рантайма (когда создается контейнер из имеджа). 

Но это не точно

**Comment by ArtemiyKroshka** [comment]
Эти переменные будут использоваться на этапе рантайма. Они были добавлены для того чтобы пользователям не нужно было настраивать настройки DB самостоятельно. Так же можно добавить .env локально в директорию проекта, и программа будет использовать переменные из локального .env файла
